server:
  port: 8086

spring:
  application:
    name: notification-service
  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [traceId=%X{traceId}, spanId=%X{spanId}] [%thread] %logger{36} - %msg%n"
  level:
    root: INFO
    car.rental.app: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: notification-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
