receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    loglevel: info

  prometheus:
    endpoint: "0.0.0.0:9464"

  otlp:
    endpoint: "http://prometheus:9090"
    tls:
      insecure: true

  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true

processors:
  batch:
  memory_limiter:
    check_interval: 5s
    limit_mib: 400
    spike_limit_mib: 100

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [logging]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [prometheus]
