server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

spring:
  application:
    name: api-gateway
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.oauth2.client.reactive.ReactiveOAuth2ClientAutoConfiguration
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:9090/realms/car-rental/protocol/openid-connect/certs}
  redis:
    host: ${REDIS_HOST:localhost}
    port: 6379
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - PreserveHostHeader
      httpclient:
        connect-timeout: 3000
        response-timeout: 10s
        pool:
          type: fixed
          max-connections: 200
          acquire-timeout: 500
      routes:
        - id: cars-service
          uri: http://car-service:8081
          predicates:
            - Path=/api/cars/**
          filters:
            - StripPrefix=1

        - id: reservations-service
          uri: lb://reservation-service
          predicates:
            - Path=/api/reservations/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: reservationsCB
                fallbackUri: forward:/fallback/reservations
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@userKeyResolver}"

        - id: user-profile-service
          uri: lb://user-profile-service
          predicates:
            - Path=/users/**

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO

gateway:
  monitoring-service:
    url: http://monitoring-service:8085/audit

monitoring:
  service:
    url: ${MONITORING_SERVICE_URL:http://monitoring-service:8085}

resilience4j:
  circuitbreaker:
    instances:
      reservationsCB:
        slidingWindowSize: 20
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
