apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: carrental
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:latest
          args: ["--car_rental_app.config=/etc/otel/car_rental_app.config.yaml"]
          volumeMounts:
            - name: otel-car_rental_app.config
              mountPath: /etc/otel
          ports:
            - containerPort: 4317
            - containerPort: 4318
            - containerPort: 9464
      volumes:
        - name: otel-car_rental_app.config
          configMap:
            name: otel-collector-car_rental_app.config
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: carrental
spec:
  selector:
    app: otel-collector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
    - name: metrics
      port: 9464
      targetPort: 9464
