server:
  port: 8085

spring:
  application:
    name: monitoring-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/monitoring}
  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [traceId=%X{traceId}, spanId=%X{spanId}] [%thread] %logger{36} - %msg%n"
  level:
    root: INFO
    car.rental.app: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: monitoring-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
